ASPNETGolfAPI/Models/ErrorViewModel.cs
using System;

namespace ASPNETGolfAPI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ASPNETGolfAPI/Models/Irankingrepos.cs
using System;
using System.Collections.Generic;

namespace ASPNETGolfAPI.Models
{
    public interface Irankingrepos
    {

        public IEnumerable<Ranking> GetAllRankings();
    }
}

ASPNETGolfAPI/Models/Rankingrepos.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json;
using RestSharp;

namespace ASPNETGolfAPI.Models
{
    public class Rankingrepos : Irankingrepos
    {
        public Rankingrepos()
        {
        }

        public IEnumerable<Ranking> GetAllRankings()
        {
            var client = new RestClient("https://golf-leaderboard-data.p.rapidapi.com/world-rankings");
            var request = new RestRequest(Method.GET);
            request.AddHeader("x-rapidapi-key", "ad097d5c45mshbc13e25e0f79185p1231e3jsn175260ba160d");
            request.AddHeader("x-rapidapi-host", "golf-leaderboard-data.p.rapidapi.com");
            IRestResponse response = client.Execute(request);
            //Console.WriteLine(response.Content);
            var golfRankings = JsonConvert.DeserializeObject<Root>(response.Content);

            var topFifty = golfRankings.results.rankings.OrderByDescending(x => x.num_wins).Take(50);

            var ranking = new Ranking();
            var ranking2 = new Ranking();

           
           return topFifty;

            //foreach (var player in topFifty)
            //{
            //    Console.WriteLine("..................");
            //    Console.WriteLine($"{player.position} {player.player_name} ");

            //}
        }
    }
}

ASPNETGolfAPI/Models/root.cs
using System;
namespace ASPNETGolfAPI.Models
{
    using System;
    using System.Collections.Generic;

    
        // Root myDeserializedClass = JsonConvert.DeserializeObject<Root>(myJsonResponse); 
        public class Fields
        {
            public string last_updated { get; set; }
        }

        public class Meta
        {
            public string title { get; set; }
            public string description { get; set; }
            public Fields fields { get; set; }
        }

        public class Ranking
        {
            public int player_id { get; set; }
            public string player_name { get; set; }
            public int position { get; set; }
            public int movement { get; set; }
            public int num_events { get; set; }
            public int num_wins { get; set; }
            public string points { get; set; }
            public int num_top_tens { get; set; }
        }

        public class Results
        {
            public DateTime last_updated { get; set; }
            public List<Ranking> rankings { get; set; }
        }

        public class Root
        {
            public Meta meta { get; set; }
            public Results results { get; set; }
        }


    

}

ASPNETGolfAPI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ASPNETGolfAPI.Models;

namespace ASPNETGolfAPI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASPNETGolfAPI/Controllers/RankingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ASPNETGolfAPI.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RestSharp;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ASPNETGolfAPI.Controllers
{
    public class RankingController : Controller
    {
        private readonly Irankingrepos repo;
        // GET: /<controller>/
        public IActionResult Index()

        {

             //var client = new RestClient("https://golf-leaderboard-data.p.rapidapi.com/world-rankings");
            var client = new RestClient("https://golf-leaderboard-data.p.rapidapi.com/tour-rankings/2/2021");

 
            var request = new RestRequest(Method.GET);
            request.AddHeader("x-rapidapi-key", "ad097d5c45mshbc13e25e0f79185p1231e3jsn175260ba160d");
            request.AddHeader("x-rapidapi-host", "golf-leaderboard-data.p.rapidapi.com");
            IRestResponse response = client.Execute(request);
            //Console.WriteLine(response.Content);
            var golfRankings = JsonConvert.DeserializeObject<Root>(response.Content);

            var topFifty = golfRankings.results.rankings.OrderByDescending(x => x.num_wins).Take(50);

           

            return View(topFifty);
        }
    }
}

ASPNETGolfAPI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ASPNETGolfAPI/Views/Ranking/Index.cshtml
@model IEnumerable<Ranking>


<h2>Golf Rankings</h2>
<table class="table">
    <tr>
        <th>Player</th>
        <th>Position</th>
        <th>Wins</th>
    </tr>
   
        @foreach (var player in Model)
        {
            <tr>
            <td>@player.player_name</td>
            <td>@player.position</td>
            <td>@player.num_wins</td>
                </tr>
        }
    
</table>

ASPNETGolfAPI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASPNETGolfAPI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASPNETGolfAPI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ranking" asp-action="Index">Golf Rankings</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ASPNETGolfAPI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>